#!/bin/bash
# Write a script that counts the number of directories and sub-directories in the current directory.
# The current and parent directories should not be taken into account
# Hidden directories should be counted

find . -type d -not -name '.' | wc -l