#!/bin/bash
# Write a script that writes into the file ls_cwd_content the result of the command ls -la. 
# if the file ls_cwd_content already exists, it should be overwritten. 
# if the file ls_cwd_content does not exisit create it

ls -ls > ls_cwd_content