#!/bin/bash

# Write a script that changes the owner and the group owner of _hello to vincent and staff respectively.
# The file _hello is in the working directory
# the file _hello is a symbolic link

chown _R vincent:staff _hello