#!/bin/bash 

# Create a script that copies all the HTML files from the current working directory to the parent 
# of the working director, but only copy files that exist in the parent of the working directory
# or were newer than the versions in the parent of the working directory.

# You can consider that all HTML files have the extension .html

cp -u *.html ../